name: CI for Angular
on: [push]
jobs:
  unit-tests:
    runs-on: unbuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependecies
        run: npm ci
      - name: Run Tests
        run: ng test --no-watch --code-coverage --browsers=Chrome
